// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/sign-in": {
    params: {};
  };
  "/sign-up": {
    params: {};
  };
  "/forgot-password": {
    params: {};
  };
  "/reset-password": {
    params: {};
  };
  "/verify-email": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/workspaces": {
    params: {};
  };
  "/workspaces/:workspaceId": {
    params: {
      "workspaceId": string;
    };
  };
  "/workspaces/:workspaceId/projects/:projectId": {
    params: {
      "workspaceId": string;
      "projectId": string;
    };
  };
  "/workspaces/:workspaceId/projects/:projectId/tasks/:taskId": {
    params: {
      "workspaceId": string;
      "projectId": string;
      "taskId": string;
    };
  };
  "/my-tasks": {
    params: {};
  };
  "/members": {
    params: {};
  };
  "/workspace-invite/:workspaceId": {
    params: {
      "workspaceId": string;
    };
  };
  "/user/profile": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/sign-in" | "/sign-up" | "/forgot-password" | "/reset-password" | "/verify-email" | "/dashboard" | "/workspaces" | "/workspaces/:workspaceId" | "/workspaces/:workspaceId/projects/:projectId" | "/workspaces/:workspaceId/projects/:projectId/tasks/:taskId" | "/my-tasks" | "/members" | "/workspace-invite/:workspaceId" | "/user/profile";
  };
  "routes/auth/auth-layout.tsx": {
    id: "routes/auth/auth-layout";
    page: "/" | "/sign-in" | "/sign-up" | "/forgot-password" | "/reset-password" | "/verify-email";
  };
  "routes/root/home.tsx": {
    id: "routes/root/home";
    page: "/";
  };
  "routes/auth/sign-in.tsx": {
    id: "routes/auth/sign-in";
    page: "/sign-in";
  };
  "routes/auth/sign-up.tsx": {
    id: "routes/auth/sign-up";
    page: "/sign-up";
  };
  "routes/auth/forgot-password.tsx": {
    id: "routes/auth/forgot-password";
    page: "/forgot-password";
  };
  "routes/auth/reset-password.tsx": {
    id: "routes/auth/reset-password";
    page: "/reset-password";
  };
  "routes/auth/verify-email.tsx": {
    id: "routes/auth/verify-email";
    page: "/verify-email";
  };
  "routes/dashboard/dashboard-layout.tsx": {
    id: "routes/dashboard/dashboard-layout";
    page: "/dashboard" | "/workspaces" | "/workspaces/:workspaceId" | "/workspaces/:workspaceId/projects/:projectId" | "/workspaces/:workspaceId/projects/:projectId/tasks/:taskId" | "/my-tasks" | "/members";
  };
  "routes/dashboard/home.tsx": {
    id: "routes/dashboard/home";
    page: "/dashboard";
  };
  "routes/dashboard/workspaces/index.tsx": {
    id: "routes/dashboard/workspaces/index";
    page: "/workspaces";
  };
  "routes/dashboard/workspaces/workspace-details.tsx": {
    id: "routes/dashboard/workspaces/workspace-details";
    page: "/workspaces/:workspaceId";
  };
  "routes/dashboard/project/project-details.tsx": {
    id: "routes/dashboard/project/project-details";
    page: "/workspaces/:workspaceId/projects/:projectId";
  };
  "routes/dashboard/task/task-details.tsx": {
    id: "routes/dashboard/task/task-details";
    page: "/workspaces/:workspaceId/projects/:projectId/tasks/:taskId";
  };
  "routes/dashboard/my-tasks.tsx": {
    id: "routes/dashboard/my-tasks";
    page: "/my-tasks";
  };
  "routes/dashboard/members.tsx": {
    id: "routes/dashboard/members";
    page: "/members";
  };
  "routes/dashboard/workspaces/workspace-invite.tsx": {
    id: "routes/dashboard/workspaces/workspace-invite";
    page: "/workspace-invite/:workspaceId";
  };
  "routes/user/user-layout.tsx": {
    id: "routes/user/user-layout";
    page: "/user/profile";
  };
  "routes/user/profile.tsx": {
    id: "routes/user/profile";
    page: "/user/profile";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/auth/auth-layout": typeof import("./app/routes/auth/auth-layout.tsx");
  "routes/root/home": typeof import("./app/routes/root/home.tsx");
  "routes/auth/sign-in": typeof import("./app/routes/auth/sign-in.tsx");
  "routes/auth/sign-up": typeof import("./app/routes/auth/sign-up.tsx");
  "routes/auth/forgot-password": typeof import("./app/routes/auth/forgot-password.tsx");
  "routes/auth/reset-password": typeof import("./app/routes/auth/reset-password.tsx");
  "routes/auth/verify-email": typeof import("./app/routes/auth/verify-email.tsx");
  "routes/dashboard/dashboard-layout": typeof import("./app/routes/dashboard/dashboard-layout.tsx");
  "routes/dashboard/home": typeof import("./app/routes/dashboard/home.tsx");
  "routes/dashboard/workspaces/index": typeof import("./app/routes/dashboard/workspaces/index.tsx");
  "routes/dashboard/workspaces/workspace-details": typeof import("./app/routes/dashboard/workspaces/workspace-details.tsx");
  "routes/dashboard/project/project-details": typeof import("./app/routes/dashboard/project/project-details.tsx");
  "routes/dashboard/task/task-details": typeof import("./app/routes/dashboard/task/task-details.tsx");
  "routes/dashboard/my-tasks": typeof import("./app/routes/dashboard/my-tasks.tsx");
  "routes/dashboard/members": typeof import("./app/routes/dashboard/members.tsx");
  "routes/dashboard/workspaces/workspace-invite": typeof import("./app/routes/dashboard/workspaces/workspace-invite.tsx");
  "routes/user/user-layout": typeof import("./app/routes/user/user-layout.tsx");
  "routes/user/profile": typeof import("./app/routes/user/profile.tsx");
};